### ISSUE TITLE
How do we deal with mutable pairs?

### ISSUE THREAD

**Issue by bkc39** [bennn/mechanics#22]
In MIT Scheme `cons` cells are mutable by default. In Racket, this is not the case. There are no analogs of `set-car!` and `set-cdr!`. What is the plan to deal with the cases that they use these features. This happens in many of their internal types.

For example,

``` scheme
(define (add-property! abstract-quantity property-name property-value)
  (if (pair? abstract-quantity)
      (set-cdr! (last-pair abstract-quantity)
        (list (list property-name property-value)))
      (error "Bad abstract quantity -- ADD-PROPERTY!")))
```

I propose that we actually make the internal structures pure and re-export the `!` versions of functions.

``` racket
(provide
  (rename-out
    [add-property add-property!]))

(define (add-property abstract-quantity property-name property-value)
  (if (pair? abstract-quantity)
      (cons (car abstract-quantity)
            (cons (cons property-name property-value)
                  (cdr abstract-quantity)))
      (error "Bad abstract quantity -- ADD-PROPERTY!")))
```

Also generally I am looking to switch the association list based data structures to racket hash maps. I think that we can define nicer interfaces and reduce boilerplate this way.

**Comment by bennn** [comment]
HashMaps are good. Structs can also be `#:mutable`. I will be sad if we have to resort to `mcons`.

**Comment by bkc39** [comment]
Yea. For the above example I have `abstract-quantity` as a `struct` that wraps a `hasheq`. I think the plan should be
- If all fields are known in advance use a `struct` with `#:mutable`.
- Otherwise use a `hash` of some sort.

That being said, so far I've come across at least 3 different types that fall into the latter case (mostly the symbolic expressions in `express`). Dealing with the maps should be more straightforward. I really miss the clojure style

``` clojure
(my-map :field :field2 :field3)
```

Would you be ok with me making some macros to replicate this type of syntax for nested map lookups?

**Comment by bennn** [comment]
Yes!
