### ISSUE TITLE
Rebasing

### ISSUE THREAD

**Issue by bkc39** [bennn/mechanics#25]
Can you please rebase onto master before merging? I don't like all this extra noise caused by all the branching.

**Comment by bennn** [comment]
`pull -r` works, right?

**Comment by bennn** [comment]
wait, how do I avoid merge commits using the github gui?

**Comment by bkc39** [comment]
[This](http://randyfay.com/content/rebase-workflow-git) is what I'm talking about.

**Comment by bennn** [comment]
I think `pull -r` accomplishes that. I think this also means we need to avoid clicking the green "merge!" button on github.

**Comment by bkc39** [comment]
I'm fine with that.
