### ISSUE TITLE
machine-ɛ

### ISSUE THREAD

**Issue by bennn** [bennn/mechanics#9]
What's the problem with `machine-ɛ` in #7 ?

My hope was that we could use `machine-ɛ` everywhere and it'd be computed at compile-time, so people using the library would get precision matching their machine.

**Comment by bkc39** [comment]
For some reason in d741443f39b54a4a7622b9470227424c92d450cd I wasn't able to get it to compile when computing `find-machine-ɛ`. I hacked around this by making everything a macro.

I just tried switching this back last night and it worked. This should be updated by the time we merge #7
